name: simple_event_notifier
description: "Simple Event Notifier - Send notifications from anywhere to anywhere. No requirement that there is a listener nor a publisher"
version: 0.0.3
homepage: https://github.com/abrovinc/flutter_simple_event_notifier

repository: https://github.com/abrovinc/flutter_simple_event_notifier
issue_tracker: https://github.com/abrovinc/flutter_simple_event_notifier/issues
contributors: Steve Widinghoff <Nosfert>

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter: